#!/bin/bash
# Quick script to display import order

echo "🏫 SCHOOLS MIGRATION - IMPORT ORDER"
echo "=================================================="
echo ""
echo "Run these files IN ORDER in Supabase SQL Editor:"
echo ""
echo "1️⃣  019_schools_system_schema.sql  (FIRST - creates table)"
echo "2️⃣  019_schools_data_part_aa.sql   (Part 1/8 - ~1,000 schools)"
echo "3️⃣  019_schools_data_part_ab.sql   (Part 2/8 - ~1,000 schools)"
echo "4️⃣  019_schools_data_part_ac.sql   (Part 3/8 - ~1,000 schools)"
echo "5️⃣  019_schools_data_part_ad.sql   (Part 4/8 - ~1,000 schools)"
echo "6️⃣  019_schools_data_part_ae.sql   (Part 5/8 - ~1,000 schools)"
echo "7️⃣  019_schools_data_part_af.sql   (Part 6/8 - ~1,000 schools)"
echo "8️⃣  019_schools_data_part_ag.sql   (Part 7/8 - ~1,000 schools)"
echo "9️⃣  019_schools_data_part_ah.sql   (Part 8/8 - ~920 schools)"
echo ""
echo "=================================================="
echo "Total: 7,920 schools across Zimbabwe"
echo ""
echo "After import, verify with:"
echo "  SELECT COUNT(*) FROM schools;"
echo "  -- Should return: 7920"
